name: build
on: [push]

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install pytest
      - run: PYTHONPATH=markdown-helper:$PYTHONPATH pytest
  flake8:
    name: coding style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: python --version
      - run: pip install flake8
      - run: flake8 markdown-helper